allergene = [
    "milch",
    "butter",
    "rahm",
    "weizen",
    "roggen",
    "gerste",
    "dinkel",
    "mandeln",
    // "erdnuss",
    // "erdnüsse",
    // "haselnuss",
    // "haselnüsse",
    "maroni",
    "pistazien",
    // "walnuss",
    // "walnüsse",
    "cashew",
    "kokos",
    "soja",
    "kaliummetabisulfit",
    "sellerie",
    "senf",
    "sesam",
    "käse",
    "thunfisch",
    "joghurt",
    "yoghurt",
    "jogurt",
    "gluten",
    "malz",
    "hafer",
    "nüsse",
    "nuss",
    "eiklar",
    "eigelb",
    "eiweiss",
    "eier",
    "eipulver",
    "eiprotein",
    "Ei gekocht",
    "fisch",
    "schwefel",
    "sulfit",
    "lupinen",
    "schnecke",
    "muschel",
    "tintenfisch",
    "laktose",
    "mayonnaise",
    "molke",
    "schalenfrüchte",
    "schalenfrucht"
]